openapi: 3.0.0
info:
  title: 'System API'
  description: "Access and control game server, players, monetization, tasks via external applications.\n\n:::warning WORK IN PROGRESS\nThis API is work in progress. Things may change.\n:::\n## 3rd party Integration\nWhen you're developing a 3rd party app that connects with the System API, you need to include your GSA-ID header with all requests.\nIf you don't have a GSA-ID yet, please contact support@gameserverapp.com.\n\n## Rate limit\nYou are rate limited to 100 requests per minute."
  contact:
    email: support@gameserverapp.com
  version: '2'
servers:
  -
    url: 'https://api.gameserverapp.com'
    description: api.gameserverapp.com
paths:
  '/system-api/v2/config-template/{configtemplate_id}/config/{location}':
    get:
      tags:
        - Config
      summary: 'Get config'
      description: 'Get a particular Config for the Config template.'
      operationId: getConfig
      security:
        -
          systemapi-passport:
            - config-template
    put:
      tags:
        - Config
      summary: 'Update config content'
      description: 'Update particular Config for Config template.'
      operationId: updateConfig
      security:
        -
          systemapi-passport:
            - config-template
  /system-api/v2/config-templates:
    get:
      tags:
        - 'Config Template'
      summary: 'All Config templates'
      description: 'Lists all Config template for the dashboard.'
      operationId: AllConfigTemplates
      security:
        -
          systemapi-passport:
            - config-template
  '/system-api/v2/config-template/{configtemplate_id}':
    get:
      tags:
        - 'Config Template'
      summary: 'Get Config template'
      description: 'Get the Config template for the provided ID.'
      operationId: getConfigTemplate
      security:
        -
          systemapi-passport:
            - config-template
    put:
      tags:
        - 'Config Template'
      summary: 'Update Config template'
      description: 'Update an existing Config template.'
      operationId: updateConfigTemplate
      security:
        -
          systemapi-passport:
            - config-template
  /system-api/v2/config-template:
    post:
      tags:
        - 'Config Template'
      summary: 'Store Config template'
      description: 'Store a new Config template.'
      operationId: storeConfigTemplate
      security:
        -
          systemapi-passport:
            - config-template
  '/system-api/v2/config-template/{configtemplate_id}/restart-servers':
    post:
      tags:
        - 'Config Template'
      summary: 'Restart Config servers'
      description: 'Restart all servers that have this Config template connected.'
      operationId: restartServersConfigTemplate
      security:
        -
          systemapi-passport:
            - config-template
  /system-api/v2/game/available:
    get:
      tags:
        - Game
      summary: 'All supported games'
      description: 'Lists all games currently supported on GSA.'
      operationId: AllGames
  /system-api/v2/gameservers:
    get:
      tags:
        - 'Game Server'
      summary: 'All game servers'
      description: 'Lists all active/installed game servers for the dashboard.'
      operationId: AllGameServers
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}':
    get:
      tags:
        - 'Game Server'
      summary: 'Get game server'
      description: 'Get the game server for the provided ID.'
      operationId: getGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/broadcast':
    post:
      tags:
        - 'Game Server'
      summary: 'Broadcast message to game server'
      description: 'Send broadcast message to game server.'
      operationId: broadcastGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/command':
    post:
      tags:
        - 'Game Server'
      summary: 'Run command on game server'
      description: 'Send command to game server.'
      operationId: commandGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/start':
    post:
      tags:
        - 'Game Server'
      summary: 'Start game server'
      description: 'Start game server.'
      operationId: startGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/update':
    post:
      tags:
        - 'Game Server'
      summary: 'Update game server'
      description: 'Schedule update for game server, with optional countdown and in-game broadcast.'
      operationId: updateGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/shutdown':
    post:
      tags:
        - 'Game Server'
      summary: 'Shutdown game server'
      description: 'Shutdown update for game server, with optional countdown and in-game broadcast.'
      operationId: shutdownGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/restart':
    post:
      tags:
        - 'Game Server'
      summary: 'Restart game server'
      description: 'Restart update for game server, with optional countdown and in-game broadcast.'
      operationId: restartGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/gameserver/{gameserver_id}/cancel':
    post:
      tags:
        - 'Game Server'
      summary: 'Cancel actions'
      description: 'Cancel scheduled game server actions'
      operationId: cancelGameServer
      security:
        -
          systemapi-passport:
            - gameserver
  '/system-api/v2/task/{task_id}/execute':
    post:
      tags:
        - Task
      summary: 'Execute task'
      description: 'Executes any `webhook` tasks.'
      operationId: executeTask
      security:
        -
          systemapi-passport:
            - task
components:
  securitySchemes:
    systemapi-passport:
      type: http
      scheme: bearer
security:
  -
    systemapi-passport: []
