

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    getting_started: [
        'getting_started',
        {
            type: 'autogenerated',
            dirName: 'getting_started',
        },
    ],

    dashboard: [
        'dashboard',
        {
            type: 'autogenerated',
            dirName: 'dashboard',
        },
    ],
};

module.exports = sidebars;