

/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    getting_started: [
        'introduction',
        {
            type: 'autogenerated',
            dirName: 'getting_started',
        },
    ],

    dashboard: [
        'dashboard',
        {
            type: 'category',
            label: 'Chat / console',
            collapsed: false,
            items: [
                'dashboard/chat_console/general',
                'dashboard/chat_console/filtering',
            ],
        },
        {
            type: 'category',
            label: 'Players',
            collapsed: false,
            items: [
                'dashboard/players/general',
                'dashboard/players/mute_player',
                'dashboard/players/kick_player',
                'dashboard/players/ban_player',
                'dashboard/players/custom_roles',
            ],
        },
    ],

    developers: [
        'developers',
        {
            type: 'autogenerated',
            dirName: 'developers',
        },
    ],
};

module.exports = sidebars;